### ISSUE TITLE
How can i install the application ?

### ISSUE THREAD

**Issue by vooveen** [projectdelta6/ADB-Stay-Awake#2]
how can i install the application in my phone please

**Comment by projectdelta6** [comment]
Hi, I don't distribute any builds of the app myself, the code is there for you to compile and install the app yourself, you can use [Android Studio](https://developer.android.com/studio) to do that

**Comment by projectdelta6** [comment]
Be sure to check the [ReadMe](https://github.com/projectdelta6/ADB-Stay-Awake#important) for the ADB command you will need to run in order to grant the app permission it needs to work

**Comment by IzzySoft** [comment]
What about "simple end-users" not having any build environment? And yes, there are some who still have good uses for ADB to be enabled – think of ScrCpy and the likes to export the display to your PC, or creating backups etc. :wink:

**Comment by projectdelta6** [comment]
To be honest if you are capable enough to get ADB installed and use things like ScrCpy, then you are certainly capable enough to install Android Studio and compile the project (imo it is easier than installing standalone ADB)

But in any case - I have put up a compiled APK [here](https://github.com/projectdelta6/ADB-Stay-Awake/tree/master/APK), please do remember to check the [ReadME](https://github.com/projectdelta6/ADB-Stay-Awake#important) for the ADB command that you will need to allow the app to work correctly.

**Comment by IzzySoft** [comment]
TBH 2, capable is one thing. But installing hundreds of MB just to keep the screen on isn't something many people would agree to :wink:

Plus the reason I've chimed in here was that I could add your app to [my repo](https://apt.izzysoft.de/fdroid)¹ – thus making it available easily, even including update notifications etc (my repo can be used with any of the [F-Droid clients](https://android.izzysoft.de/applists/category/named/apps_markets#group_1181)). Which I have done now: it will [become available here](https://apt.izzysoft.de/fdroid/index/apk/com.duck.stayawakeadb) with the next sync around 6 pm UTC. Updates will be fetched whenever you make a new APK available – which my updater currently looks for in the specified directory (should you switch to [tagged releases](https://github.com/projectdelta6/ADB-Stay-Awake/releases) and attach the APKs there (or move the location otherwise), please drop me a note so I update the metadata here.

Thanks a lot, also for the Readme-update! Be welcome to point to the above link from your Readme and, if you wish, to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) for that purpose :smiley:

----

¹ <sub>it's the second largest known F-Droid repo with currently about 900 apps, only topped by F-Droid's own with close to 4k apps</sub>
